# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0002_auto_20160516_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='img/deafult', upload_to='img/'),
            preserve_default=False,
        ),
    ]
