# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0005_auto_20160519_2240'),
        ('wood', '0004_auto_20160520_1557'),
    ]

    operations = [
    ]
