# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0009_auto_20160704_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('comment', models.TextField(verbose_name='Дополнительная информация')),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.Product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
