# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0014_auto_20160921_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
